name: CD

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_bazel_slsa3.yml@07e64b653f10a80b6510f4568f685f8b7b9ea830 # v1.9.0
    with:
      targets: "//pkg/tidydns:go_default_library"
